// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsqCRJYlaahaZMYxLOXwUuTMBtbvLt9DE',
    appId: '1:1099342614751:web:6c9237a3d495b36649996a',
    messagingSenderId: '1099342614751',
    projectId: 'sales-flow-62ec6',
    authDomain: 'sales-flow-62ec6.firebaseapp.com',
    storageBucket: 'sales-flow-62ec6.firebasestorage.app',
    measurementId: 'G-4DZTJ4KQZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJQEraZ5T7EUWrWzq1bUxzN_T0EQQX-mo',
    appId: '1:1099342614751:android:701975e1897f3f4649996a',
    messagingSenderId: '1099342614751',
    projectId: 'sales-flow-62ec6',
    storageBucket: 'sales-flow-62ec6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ATAPAquNddyckd96NK3JnuoXCOMHHK4',
    appId: '1:1099342614751:ios:34054fcbc84159d549996a',
    messagingSenderId: '1099342614751',
    projectId: 'sales-flow-62ec6',
    storageBucket: 'sales-flow-62ec6.firebasestorage.app',
    iosBundleId: 'com.example.salesFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ATAPAquNddyckd96NK3JnuoXCOMHHK4',
    appId: '1:1099342614751:ios:34054fcbc84159d549996a',
    messagingSenderId: '1099342614751',
    projectId: 'sales-flow-62ec6',
    storageBucket: 'sales-flow-62ec6.firebasestorage.app',
    iosBundleId: 'com.example.salesFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsqCRJYlaahaZMYxLOXwUuTMBtbvLt9DE',
    appId: '1:1099342614751:web:06484af55a5b0c3a49996a',
    messagingSenderId: '1099342614751',
    projectId: 'sales-flow-62ec6',
    authDomain: 'sales-flow-62ec6.firebaseapp.com',
    storageBucket: 'sales-flow-62ec6.firebasestorage.app',
    measurementId: 'G-T95S9FLDYL',
  );
}
